// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_just_a_distant_memory = "CgkIuKrc7IwREAIQAw"; // <GPGSID>
        public const string achievement_jill_would_be_proud = "CgkIuKrc7IwREAIQBQ"; // <GPGSID>
        public const string leaderboard_41 = "CgkIuKrc7IwREAIQAA"; // <GPGSID>
        public const string achievement_reconstructed_memory = "CgkIuKrc7IwREAIQCA"; // <GPGSID>
        public const string achievement_lumos_maxima = "CgkIuKrc7IwREAIQBg"; // <GPGSID>
        public const string achievement_syllogomania = "CgkIuKrc7IwREAIQBA"; // <GPGSID>
        public const string achievement_triple_parked = "CgkIuKrc7IwREAIQCw"; // <GPGSID>
        public const string achievement_notsofake_exorcist = "CgkIuKrc7IwREAIQAg"; // <GPGSID>
        public const string achievement_a_promise_made_is_a_promise_kept = "CgkIuKrc7IwREAIQCQ"; // <GPGSID>
        public const string achievement_whats_in_the_box = "CgkIuKrc7IwREAIQBw"; // <GPGSID>
        public const string achievement_neversaydie_kinda_guy = "CgkIuKrc7IwREAIQCg"; // <GPGSID>

}

